version: "3"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LIBRARY_DIR}/heimdall:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - ${LIBRARY_DIR}/plex:/config      
      - ${FILMS_DIR}:/films
      - ${TV_DIR}:/tv
    depends_on:
      - radarr
      - sonarr
    restart: unless-stopped
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      # - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
  vpn:
    container_name: vpn
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
      - 7878:7878 # radarr
      - 8989:8989 # sonarr
      - 8191:8191 # flaresolverr
      - 9117:9117 # jackett
      - 5055:5055 # overseer
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER="$NORD_USER"
      - OPENVPN_PASSWORD="$NORD_PASS"
      - SERVER_COUNTRIES=$NORD_COUNTRY
      - VPN_TYPE=openvpn
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - FIREWALL_OUTBOUND_SUBNETS=192.168.178.0/24
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=$PUID
      - UGID=$PGID
      - TZ=$TZ
    volumes:
      - $LIBRARY_DIR/transmission:/config
      - ${DOWNLOAD_DIR}:/downloads
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    depends_on:
      - vpn
    network_mode: service:vpn

  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LIBRARY_DIR}/radarr:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${FILMS_DIR}:/films
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    depends_on:
      - vpn
      - transmission
    network_mode: service:vpn

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LIBRARY_DIR}/sonarr:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${TV_DIR}:/tv
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    depends_on:
      - vpn
      - transmission
    network_mode: service:vpn
  
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=hcaptcha-solver
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    depends_on:
      - vpn
      - radarr
      - sonarr
    network_mode: service:vpn

  jackett:
    image: ghcr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - AUTO_UPDATE=true
      - RUN_OPTS=
    volumes:
      - $LIBRARY_DIR/jackett:/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    depends_on:
      - vpn
      - flaresolverr
    network_mode: service:vpn

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LIBRARY_DIR}/overseerr:/app/config
    restart: unless-stopped
    depends_on:
      - vpn
      - sonarr
      - radarr
    network_mode: service:vpn
