version: "3"
services:
  server:
    image: docker.gitea.com/gitea:latest
    container_name: gitea
    environment:
      USER: james
      USER_UID: 1000
      USER_GID: 1000
    restart: always
    networks:
      - gitea
    volumes:
      - $GIT_DIR:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"

  vpn:
    container_name: vpn
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 9091:9091 # Transmission
      - 51413:51413
      - 51413:51413/udp
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER="$NORD_USER"
      - OPENVPN_PASSWORD="$NORD_PASS"
      - SERVER_COUNTRIES=$NORD_COUNTRY
      - VPN_TYPE=openvpn
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - FIREWALL_OUTBOUND_SUBNETS=192.168.178.0/24
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $LIBRARY_DIR/transmission:/config
      - $DOWNLOAD_DIR:/downloads
    network_mode: service:vpn
    depends_on:
      - vpn
    restart: unless-stopped

  pyload-ng:
    image: lscr.io/linuxserver/pyload-ng:latest
    container_name: pyload-ng
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $LIBRARY_DIR/pyload-ng:/config
      - $DOWNLOAD_DIR/pyload:/downloads
    ports:
      - 8888:8000 # Pyload
      - 9666:9666 # Pyload: optional
    restart: unless-stopped

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LIBRARY_DIR}/heimdall:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - ${LIBRARY_DIR}/plex:/config
      - ${FILMS_DIR}:/films
      - ${TV_DIR}:/tv
      - ${OTHERS_DIR}:/others
    depends_on:
      - radarr
      - sonarr
    restart: unless-stopped
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      # - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469

  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LIBRARY_DIR}/radarr:/config
      - $DOWNLOAD_DIR:/downloads
      - ${FILMS_DIR}:/films
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    depends_on:
      - vpn
      - transmission
    ports:
      - 7878:7878

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LIBRARY_DIR}/sonarr:/config
      - $DOWNLOAD_DIR:/downloads
      - ${TV_DIR}:/tv
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    depends_on:
      - vpn
      - transmission
    ports:
      - 8989:8989

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $LIBRARY_DIR/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LIBRARY_DIR}/overseerr:/app/config
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr
    ports:
      - 5055:5055 # overseer

  samba:
    image: dperson/samba
    container_name: samba
    environment:
      TZ: $TZ
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - $DOWNLOAD_DIR:/downloads
    command: '-s "Downloads;/downloads;yes;no;no;james" -u "$SAMBA_USER;$SAMBA_PASS" -p'
