#!/usr/bin/env zsh

echo "stopping service"
sudo systemctl stop mediaservice.service
echo "service stopped, restarting"
sudo systemctl start mediaservice.service &
echo "use ./service-logs to check startup progress"
