#!/usr/bin/env zsh

echo "stopping service"
sudo systemctl stop mediaservice.service
if [[ "$?" != "0" ]]; then
  echo "Could not stop service"
  exit 1
fi

echo "service stopped, restarting"
sudo systemctl start mediaservice.service &
echo "use ./service-logs to check startup progress"
