#!/usr/bin/env zsh

sudo systemctl stop mediaserver.service &
if [[ "$?" != "0" ]]; then
  echo "Service stop failed!"
else
  echo "service stopping, use ./service-logs to check progress, or docker ps/docker stats"
fi
